#!/bin/sh

canon_path() {
    ARG=$1
    echo $(cd $(dirname "$ARG") && pwd -P)/$(basename "$ARG")
}

LOAD_S=$(canon_path $0)
LOAD_DIR=$(dirname "${LOAD_S}")

EDITOR="emacs -nw"

PATHS_FILE=paths.txt

load_edit () {
    eval "$EDITOR" "${LOAD_S}"
}

install_edit () {
    eval "$EDITOR ${LOAD_DIR}/install"
}

tools_edit () {
    eval "$EDITOR" "${LOAD_DIR}/tools"
}

dirs_edit () {
    eval "$EDITOR" "${LOAD_DIR}/dirs"
}

aliases_edit () {
    eval "$EDITOR" "${LOAD_DIR}/aliases"
}

paths_edit () {
    eval "$EDITOR" "${LOAD_DIR}/${PATHS_FILE}"
}

paths_update () {
    for LINE in $(cat ${LOAD_DIR}/${PATHS_FILE} | awk '{ print $1 }')
    do
	PATH=$PATH:$LINE
    done
}

paths_clean () {
    rm "$EDITOR" "${LOAD_DIR}/${PATHS_FILE}"
}

load_update () {
    . ${LOAD_S}
}

load_install () {
    sh ${LOAD_DIR}/install -i ${LOAD_S}
}

load_deinstall () {
    sh ${LOAD_DIR}/install -d
}

. ${LOAD_DIR}/aliases
. ${LOAD_DIR}/dirs
. ${LOAD_DIR}/tools

paths_update
