#!/bin/sh
ARGS=$@
CNT=$#

UNIQ="#unique_string_generated_from_dima_tools_script"
DIR=links

FILENAME=$(cd $(dirname "$0") && pwd -P)/paths.txt

SC=$(cd $(dirname "$0") && pwd -P)/$DIR

resolve_options() {
    CNT=${1:-0}
    ARGS=$@
    
    if [ $CNT -lt 1 ]
    then
	INSTALL=1
	return
    fi

    while [ $CNT -ne 0 ]
    do
	shift
	ARG=$1

	CNT=$(expr $CNT - 1)
	
        case $ARG in
	-i|--install)
	    INSTALL=1
	    ;;
	-d|--deinstall)
	    DEINSTALL=1
	    ;;
	*)
	    UNKNOWN=1
	    ;;
	esac
    done
}

clean_unique() {
    FILENAME=$1
    if [ -e "$FILENAME" ]
    then
	sed -i "/$UNIQ/d" $FILENAME
    fi
}

install_script() {
    SC=$1
    mkdir -p "$SC"

    ##### generate symlinks
    find . -mindepth 2 -type f -executable | grep -v ".git" | awk -v "DIR=$DIR" -f parse_path
#####

    clean_unique $FILENAME
    
    echo "$SC $UNIQ" >> $FILENAME
}

deinstall_script() {
    SC=$1
    
    rm -rf "$SC"

    clean_unique
}

resolve_options $CNT $ARGS

if [ "$UNKNOWN" = "1" ]
then
    echo "Incorrect operation was entered"
    exit 1
elif [ "$INSTALL" = "1" ]
then
    install_script $SC
elif [ "$DEINSTALL" = "1" ]
then
     deinstall_script $SC
else
    echo "Incorrect operation was entered"
    exit 1
fi
