#!/bin/sh
ARGS=$@
CNT=$#

resolve_path() {
    ROOT=$1
    PART=$2
    echo $(cd $(dirname "$ROOT") && pwd -P)/"$PART"
}

ROOT=$0
FILENAME=$(resolve_path "$ROOT" paths.txt)

resolve_options() {
    CNT=${1:-0}
    ARGS=$@
    
    if [ $CNT -lt 1 ]
    then
	INSTALL=1
	return
    fi

    while [ $CNT -ne 0 ]
    do
	shift
	ARG=$1

	CNT=$(expr $CNT - 1)
	
        case $ARG in
	-i|--install)
	    INSTALL=1
	    ;;
	-d|--deinstall)
	    DEINSTALL=1
	    ;;
	*)
	    UNKNOWN=1
	    ;;
	esac
    done
}

aliases() {
    ROOT=$1
    CUR_DIR=$(cd $(dirname "$ROOT") && pwd -P)
    
    for EL in $(find "${CUR_DIR}" -mindepth 2 -type f -executable | grep -v ".git")
    do
	if [ "$DEINSTALL" = "1" ]
        then
	    unalias $(basename $EL)
	fi
	
	if [ "$INSTALL" = "1" ]
	then
	    alias $(basename $EL)=$EL
	fi
    done
}

resolve_options $CNT $ARGS
aliases "$ROOT"
